# Provision servers
- hosts: all
  user: vagrant
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  roles:
    - common

- hosts: kafka
  #user: ansible
  become: yes
  gather_facts: yes
  roles:
  - role: kafka
